// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6pIH5wkj1Zpk6bpvopOv_SM0XwoeZiU',
    appId: '1:149108991969:web:d8bcc89217b3be0d66d4a0',
    messagingSenderId: '149108991969',
    projectId: 'worldvoice-37896',
    authDomain: 'worldvoice-37896.firebaseapp.com',
    storageBucket: 'worldvoice-37896.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAkQ1sadtXc_JDWHuWKSF_sLmZMrDKFs',
    appId: '1:149108991969:ios:a2848fe60152918266d4a0',
    messagingSenderId: '149108991969',
    projectId: 'worldvoice-37896',
    storageBucket: 'worldvoice-37896.firebasestorage.app',
    androidClientId: '149108991969-9maiuamd49io8o7dfsleo5cbqjsnaovs.apps.googleusercontent.com',
    iosClientId: '149108991969-acjjav1oedc0oo1t240sfes9fanoj7ai.apps.googleusercontent.com',
    iosBundleId: 'com.worldvoice.worldvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByAkQ1sadtXc_JDWHuWKSF_sLmZMrDKFs',
    appId: '1:149108991969:ios:a2848fe60152918266d4a0',
    messagingSenderId: '149108991969',
    projectId: 'worldvoice-37896',
    storageBucket: 'worldvoice-37896.firebasestorage.app',
    androidClientId: '149108991969-9maiuamd49io8o7dfsleo5cbqjsnaovs.apps.googleusercontent.com',
    iosClientId: '149108991969-acjjav1oedc0oo1t240sfes9fanoj7ai.apps.googleusercontent.com',
    iosBundleId: 'com.worldvoice.worldvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL6pIH5wkj1Zpk6bpvopOv_SM0XwoeZiU',
    appId: '1:149108991969:web:c9d7d97f6d1d26bd66d4a0',
    messagingSenderId: '149108991969',
    projectId: 'worldvoice-37896',
    authDomain: 'worldvoice-37896.firebaseapp.com',
    storageBucket: 'worldvoice-37896.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOpnQL6_Hcpe7nrmHlrmxmRkHqO4_Udn8',
    appId: '1:149108991969:android:b09d15308f8f5d9266d4a0',
    messagingSenderId: '149108991969',
    projectId: 'worldvoice-37896',
    storageBucket: 'worldvoice-37896.firebasestorage.app',
  );
}
